linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocritic
    - gocyclo
    - misspell
    - unconvert
    - dupl
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 25  # Higher threshold for test files and TUI code
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - octalLiteral      # 0750 is more readable than 0o750
      - hugeParam         # Passing styles by value is idiomatic in Lip Gloss
      - evalOrder         # Defer expressions are intentionally evaluated at defer time
      - nestingReduce     # Style preference
  gosec:
    excludes:
      - G104 # Audit errors not checked - we'll handle explicitly

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
